name: tests
run-name: Run Tests
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    tests:
        name: 'Node.js v${{ matrix.node }}'
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node:
                    - 18
        env:
            DB_ROOT_PASSWORD: password
            DB_HOST: localhost
            DB_PORT: 5432
            DB_NAME: app_db
            DB_USER: admin
            DB_PASSWORD: password
            DB_SCHEMA: public
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: npm install
            - name: Start DB container
              run: npm run docker
            - name: Run Tests
              run: npm test
